const actions = {
  VIEW_DETAILS: "VIEW_DETAILS",
  FETCH_USER_PROFILE: "FETCH_USER_PROFILE",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
  ADD_GENRE_PREFERENCE: "ADD_GENRE_PREFERENCE",
  ADD_LANGUAGE_PREFERENCE: "ADD_LANGUAGE_PREFERENCE",
  ADD_COMPANY_PREFERENCE: "ADD_COMPANY_PREFERENCE",
  DELETE_GENRE_PREFERENCE: "DELETE_GENRE_PREFERENCE",
  DELETE_LANGUAGE_PREFERENCE: "DELETE_LANGUAGE_PREFERENCE",
  DELETE_COMPANY_PREFERENCE: "DELETE_COMPANY_PREFERENCE"
};

export default actions;
