const actions = {
  VIEW_DETAILS: "VIEW_DETAILS",
  SET_PROMISE_PENDING: "SET_PROMISE_PENDING",
  SET_PROMISE_FULFILLED: "SET_PROMISE_FULFILLED",
  SET_PROMISE_REJECTED: "SET_PROMISE_REJECTED",
  UPDATE_DASHBOARD_MOVIES: "UPDATE_DASHBOARD_MOVIES",
  FETCH_USER_PROFILE: "FETCH_USER_PROFILE",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
  FETCH_ALL_GENERS: "FETCH_ALL_GENERS",
  FETCH_ALL_LANGUAGES: "FETCH_ALL_LANGUAGES",
  FETCH_ALL_COMPANIES: "FETCH_ALL_COMPANIES",
  ADD_GENRE_PREFERENCE: "ADD_GENRE_PREFERENCE",
  ADD_LANGUAGE_PREFERENCE: "ADD_LANGUAGE_PREFERENCE",
  ADD_COMPANY_PREFERENCE: "ADD_COMPANY_PREFERENCE",
  DELETE_GENRE_PREFERENCE: "DELETE_GENRE_PREFERENCE",
  DELETE_LANGUAGE_PREFERENCE: "DELETE_LANGUAGE_PREFERENCE",
  DELETE_COMPANY_PREFERENCE: "DELETE_COMPANY_PREFERENCE"
};

export const appConstants = {
  defaultProfileImage: "images/profile-image.png"
};

export default actions;
