const actions = {
  VIEW_DETAILS: "VIEW_DETAILS",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  ADD_GENRE_PREFERENCE: "ADD_GENRE_PREFERENCE",
  ADD_LANGUAGE_PREFERENCE: "ADD_LANGUAGE_PREFERENCE",
  ADD_COMPANY_PREFERENCE: "ADD_COMPANY_PREFERENCE"
};

export default actions;
